name: Verificar Qualidade do Código

on:
  pull_request:
  workflow_dispatch:

jobs:
  check_code_quality:
    name: Verificar Qualidade do Código
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Verificar o Código-Fonte
        uses: actions/checkout@v3

      - name: Configurar o Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Instalar Dependências do Projeto
        run: npm ci

      - name: Executar Linting
        run: npm run eslint:check

      - name: Verificar Formatação
        run: npm run eslint:write