name: Code Quality Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  code_quality_verification:
    name: Code Quality Verification
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Set Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Project Dependencies
        run: npm ci

      - name: Run Code Linting
        run: npm run lint
